config/routes.rb
Rails.application.routes.draw do
  root 'videos#show'
  
  get 'admin/videos'
  get 'admin/review/:id' => 'admin#review', :as => 'admin_review'
  post 'admin/approve' => 'admin#approve'
  get 'admin/vc_relations'
  post 'admin/vc_relations'
  get 'admin/vc_approve'

  get 'competitions/admin' => 'competitions#admin'
  get 'competitions/show_videos' => 'competitions#show_videos'
  post 'competitions/add_videos' => 'competitions#add_videos'
  get 'competitions/delete_videos' => 'competitions#delete_videos'

  resource :video_cart, only: [:show]
  resources :video_carts, only: [:destroy]
  resources :added_videos, only: [:create, :update, :destroy]
  resources :password_resets
  
  get 'register' => 'users#new', :as => 'register'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'videos/:id' => 'videos#show', :as => 'video_search'
  get 'videos/:search_params' => 'videos#search'
  post '/rate' => 'rater#create', :as => 'rate'

  
  resources :users, :sessions, :rater, :upload_videos, :videos, :admin, :competitions
  resources :videos do
    member do
      put "like" => "videos#upvote"
      put "unlike" => "videos#downvote"
    end
  end

end

app/models/competition.rb
class Competition < ActiveRecord::Base
	validates_presence_of :title
	validates_presence_of :start_date
	validates_presence_of :period
	validates_presence_of :prize
	validates_presence_of :prize_num
	validates_presence_of :poster

	validates :title, length: { minimum: 2 }
		validates :title, length: { maximum: 50 }
		validates :desc, length: { maximum: 500 }

		validates_format_of :title, :with => /\A[0-9a-zA-Z\s\.\-\_]+\z/, :on => :create
	validates_format_of :period, :with => /\A([0-9])+\Z/i, :on => :create
	validates_format_of :prize, :with => /\A([0-9]+)\Z/i, :on => :create
	validates_format_of :prize_num, :with => /\A([0-9]+)\Z/i, :on => :create

	validates :period, numericality: { only_integer: true, greater_than: 0 }
	validates :prize, numericality: { only_integer: true, greater_than: 0 }
	validates :prize_num, numericality: { only_integer: true, greater_than: 0 }

	has_many :vc_relations

	before_save :clean_link

	def clean_link
		self.poster = self.poster.split('amazonaws.com/').last
	end
end

app/controllers/competitions_controller.rb
require 'date'
# require 'active_support/core_ext/string'
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy]
  before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]

  @@PER_PAGE = 9

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
  end

  def admin
    @competitions = Competition.all
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
    sql = "SELECT *, (rs.upvotes - rs.downvotes) AS votes FROM (
            SELECT videos.*,
                    sum(case when vote_flag = 1 then 1 else 0 end) AS upvotes,
                    sum(case when vote_flag = 0 then 1 else 0 end) AS downvotes
            FROM videos LEFT JOIN votes ON videos.id = votes.votable_id GROUP BY videos.id) AS rs 
          WHERE id IN (SELECT video_id FROM vc_relations WHERE competition_id = #{@competition.id} and is_approved = 1) ORDER BY votes DESC, upvotes DESC"
    @videos = Video.paginate_by_sql(sql, page: params[:page], per_page: @@PER_PAGE)
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    str = competition_params['start_date(1i)'] + '-' + competition_params['start_date(2i)'] + '-' + competition_params['start_date(3i)']
    date = DateTime.parse(str)
    date = date + competition_params[:period].to_f.days
    formatted_date = date.strftime('%Y-%m-%d')
    @competition = Competition.new(competition_params.merge!(:end_date => formatted_date))

    respond_to do |format|
      if @competition.save
        format.html { redirect_to competitions_admin_path, notice: 'Competition was successfully created.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    @competition_params_update = competition_params
    # puts @competition_params_update[:poster]
    if(@competition_params_update[:poster] == "")
      @competition_params_update.delete :poster
    end
    # puts @competition_params_update
    respond_to do |format|
      if @competition.update(@competition_params_update)
        format.html { redirect_to competitions_admin_path, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_admin_path, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_videos
    session[:competition_id] = params[:cid]
    # puts params[:cid] + "----------------------"
    sql = "SELECT * FROM videos where id not in (select video_id from vc_relations where competition_id = #{params[:cid]})"
    @param = ""
    if params.has_key?(:search)
      param = params[:search]
      @param = param
      sql = sql + " AND (title LIKE '%#{param}%' || video_desc LIKE '%#{param}%' || tags LIKE '%#{param}%')"
    end
    @count = VcRelation.where(competition_id: params[:cid]).count('id')
    @videos = Video.paginate_by_sql(sql, page: params[:page], per_page: @@PER_PAGE)
    @competition = Competition.where(id: params[:cid]).first
    if @videos.count == 0 || !@competition
      redirect_to competitions_admin_path
    end
  end

  def add_videos
    @vc_relation = VcRelation.new(video_id: params[:vid], competition_id: params[:id])
    if @vc_relation.save
      count = VcRelation.where(competition_id: params[:id]).count('id')
      render :json => "{\"msg\": \"This video has been added to the competition successfully.\", \"size\": #{count}}"
    else
      render :json => "{\"error\": \"This video was already in the competition.\"}"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.where(id: params[:id]).first
      if !@competition 
        redirect_to action: "index"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:title, :desc, :start_date, :period, :prize, :prize_num, :poster)
    end

    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "competitions/#{SecureRandom.uuid}/poster", success_action_status: '201', acl: 'public-read')
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_edit_form.html.erb
<%= form_for(@competition, html: { class: 'directUploadCompetitionEdit', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
  <% if @competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% @competition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id="error_msg">
    <ul></ul>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :size => 60, :max => 50, placeholder: "(between 2-50 characters)"%>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc, :cols => 100, :rows => 10, :max => 500, placeholder: "(less than 500 characters)" %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :period %><br>
    <%= f.text_field :period %>
  </div>
  <div class="field">
    <%= f.label :prize %><br>
    <%= f.text_field :prize %>
  </div>
  <div class="field">
    <%= f.label :prize_num %><br>
    <%= f.text_field :prize_num %>
  </div>
  <div class="field">
    <%= f.label :poster %><br>
    <input type="file" name="competition[poster]" id="competition_poster_update">
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competitions/_form.html.erb
<%= form_for(@competition, html: { class: 'directUploadCompetition', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
  <% if @competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% @competition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id="error_msg">
    <ul></ul>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :size => 60, :max => 50, placeholder: "(between 2-50 characters)"%>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc, :cols => 100, :rows => 10, :max => 500, placeholder: "(less than 500 characters)" %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :period %><br>
    <%= f.text_field :period %>
  </div>
  <div class="field">
    <%= f.label :prize %><br>
    <%= f.text_field :prize %>
  </div>
  <div class="field">
    <%= f.label :prize_num %><br>
    <%= f.text_field :prize_num %>
  </div>
  <div class="field">
    <%= f.label :poster %><br>
    <%= f.file_field :poster %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competitions/_voting.html.erb
<div class="upvote">
  <%= image_tag "like.png", size: "32x32", alt: "like" %> 
  <span class="like-vote-<%= video.id %>"><%= video.get_upvotes(vote_scope: "competition_" + competition_id.to_s).size %></span>
 </div>
<div class="downvote">
	<%= image_tag "dislike.png", size: "32x32", alt: "dislike" %> 
  <span class="unlike-vote-<%= video.id %>"><%= video.get_downvotes(vote_scope: "competition_" + competition_id.to_s).size %></span>
</div>
<div class="clear"></div>

app/views/competitions/admin.html.erb
<div class="right-content-heading">
  <div class="right-content-heading-left">
    <h3>Listing Competitions</h3>
  </div>
  <div class="clear"> </div>
  <p id="notice"><%= notice %></p>
</div>



<div class="function_bar">
<%= link_to '<< Back to upper level', admin_index_path%> |
<%= link_to 'New Competition', new_competition_path %>
<hr>
</div>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Period</th>
      <th>Prize</th>
      <th>Prize num</th>
      <th>Poster</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= competition.title %></td>
        <td><%= competition.desc %></td>
        <td><%= competition.start_date %></td>
        <td><%= competition.end_date %></td>
        <td><%= competition.period %></td>
        <td><%= competition.prize %></td>
        <td><%= competition.prize_num %></td>
        <td><%= competition.poster %></td>
        <td><%= link_to 'Show', competition, target: "_blank" %></td>
        <td><%= link_to 'Edit', edit_competition_path(competition) %></td>
        <td><%= link_to 'Delete', competition, method: :delete, data: { confirm: 'Do you want to delete this competition?' } %></td>
        <td><%= link_to 'Add videos', "show_videos?cid=#{competition.id}" %></td>
        <td><%= link_to 'Show videos list', video_cart_path(:cid => competition.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/competitions/edit.html.erb
<div class="right-content-heading">
  <div class="right-content-heading-left">
    <h3>Editing Competition</h3>
  </div>
  <div class="clear"> </div>
</div>

<%= render 'edit_form' %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_admin_path %>

app/views/competitions/index.html.erb
<h1></h1>
<div class="right-content-heading">
  <div class="right-content-heading-left">
    <h3>Listing Competitions</h3>
  </div>
  <!-- <div class="right-content-heading-right">
    <div class="social-icons">
              <ul>
                  <li><a class="facebook" href="#" target="_blank"> </a></li>
                  <li><a class="twitter" href="#" target="_blank"></a></li>
                  <li><a class="googleplus" href="#" target="_blank"></a></li>
                  <li><a class="pinterest" href="#" target="_blank"></a></li>
                  <li><a class="dribbble" href="#" target="_blank"></a></li>
                  <li><a class="vimeo" href="#" target="_blank"></a></li>
              </ul>
    </div>
  </div> -->
  <div class="clear"> </div>
</div>
<div class="video-index">
  <ul>
    <% @competitions.each do |competition| %>
      <li>
      <%= link_to "competitions/#{competition.id}" do %>
        <%= link_to image_tag(full_url(competition.poster), :style=> "max-height:100px;"), "competitions/#{competition.id}" %>
        <h3><%= link_to "#{competition.title}", "competitions/#{competition.id}" %></h3>
        <p><%= competition.desc %></p>
        <table>
          <tbody>
            <tr>
              <td style="padding: 10px 20px 10px 0px;">
                <a href="#" class="ph-button ph-btn-green">
                  Prize Money: $<%= competition.prize %> 
                </a>
              </td>
              <td style="padding: 10px 20px 10px 0px;">
                <a href="#" class="ph-button ph-btn-blue">
                  Top <%= competition.prize_num %> <%= 'Entry'.pluralize(competition.prize_num) %> win 
                </a>
              </td>
              <td style="padding: 10px 20px 10px 0px;">
                <a href="#" class="ph-button ph-btn-red">
                  <% if Date.today.mjd - competition.start_date.mjd > competition.period %>
                  Competition Over
                  <% else %>
                  <%= competition.period - (Date.today.mjd - competition.start_date.mjd) + 1 %> <%= 'day'.pluralize(competition.period - (Date.today.mjd - competition.start_date.mjd) + 1) %> left
                  <% end %>
                </a>
              </td>
            </tr>
          </tbody>
        </table>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/competitions/new.html.erb
<h1></h1>
<div class="right-content-heading">
  <div class="right-content-heading-left">
    <h3>New Competition</h3>
  </div>
  <!-- <div class="right-content-heading-right">
    <div class="social-icons">
              <ul>
                  <li><a class="facebook" href="#" target="_blank"> </a></li>
                  <li><a class="twitter" href="#" target="_blank"></a></li>
                  <li><a class="googleplus" href="#" target="_blank"></a></li>
                  <li><a class="pinterest" href="#" target="_blank"></a></li>
                  <li><a class="dribbble" href="#" target="_blank"></a></li>
                  <li><a class="vimeo" href="#" target="_blank"></a></li>
              </ul>
    </div>
  </div> -->
  <div class="clear"> </div>
</div>

<%= render 'form' %>

<%= link_to 'Back', competitions_admin_path %>

app/views/competitions/show.html.erb
<div class="right-content-heading">
  <div class="right-content-heading-left">
    <% if @is_search %>
    <h3>Search Results for <span class="keyword">"<%= @param%>"</span></h3>
    <% else %>
    <h3><%= @competition.title %></h3>
    <% end %>
  </div>
  <div class="right-content-heading-right">
    <div class="social-icons">
      <ul>
        <li><a class="facebook" href="#" target="_blank"></a></li>
        <li><a class="twitter" href="#" target="_blank"></a></li>
        <li><a class="googleplus" href="#" target="_blank"></a></li>
        <li><a class="pinterest" href="#" target="_blank"></a></li>
        <li><a class="dribbble" href="#" target="_blank"></a></li>
        <li><a class="vimeo" href="#" target="_blank"></a></li>
      </ul>
    </div>
  </div>
  <div class="clear"> </div>
</div>

<div class="video-show" style="background:#eee; margin-bottom:20px;">
  <ul>
      <li>
        <%= image_tag(full_url(@competition[:poster]), :style=> "max-height:100px;") %>
        <h3><%= @competition.title.humanize %></h3>
        <p><%= @competition.desc %></p>
        <table>
          <tbody>
            <tr>
              <td style="padding: 10px 20px 10px 0px;">
                <a href="#" class="ph-button ph-btn-green">
                  Prize Money: $<%= @competition.prize %> 
                </a>
              </td>
              <td style="padding: 10px 20px 10px 0px;">
                <a href="#" class="ph-button ph-btn-blue">
                  Top <%= @competition.prize_num %> <%= 'Entry'.pluralize(@competition.prize_num) %> win 
                </a>
              </td>
              <td style="padding: 10px 20px 10px 0px;">
                <a href="#" class="ph-button ph-btn-red">
                  <% if Date.today.mjd - @competition.start_date.mjd > @competition.period %>
                  Competition Over
                  <% else %>
                  <%= @competition.period - (Date.today.mjd - @competition.start_date.mjd) + 1 %> <%= 'day'.pluralize(@competition.period - (Date.today.mjd - @competition.start_date.mjd) + 1) %> left
                  <% end %>
                </a>
              </td>
            </tr>
          </tbody>
        </table>
      </li>
  </ul>
  </div>

<div class="content-grids">
  <div>
  <ul class="video-browsing">
    <% if @videos.count == 0 %>
      <div>
        <span>There is no videos in this competition yet.</span>
      </div>
    <% else %>
      <% @videos.each do |v| %>
      <div class="content-grid">
        <%= link_to image_tag(full_url(v.poster_url)), "#{videos_path}/#{v.id}?cid=#{@competition.id}", title: v.title, class: "video-link", data: { no_turbolink: true } %>
        <h3><%= v.title %></h3>
        <%= render partial: "voting", locals: {video: v, competition_id: @competition.id} %>
        <%= link_to "Watch now", "#{videos_path}/#{v.id}?cid=#{@competition.id}", title: v.title, class: "button", data: { no_turbolink: true } %>
      </div>
      <% end %>
    <% end %>
  </ul>
  </div>
  <div class="clear"> </div>
  <%= will_paginate @videos %>
  <div class="clear"> </div>
</div>

app/views/competitions/show_videos.html.erb
<div class="right-content-heading">
	<div class="right-content-heading-left">
		<h3>Add videos to "<%= @competition.title %>" 
		<% if @param != "" %>
		<%= "(search results for \"#{@param})\"" %>
		<% end %>
		</h3>
		<h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
	</div>
	<div class="clear"> </div>
	<div class="search">
          <%= form_tag competitions_show_videos_path(), :method => 'get' do %>
          <%= hidden_field_tag :cid, params[:cid] %>
          <%= text_field_tag :search, params[:search], placeholder: "Search" %> 
          <%= submit_tag "", :name => nil %>
          <% end %>
        </div>
</div>

<%= link_to 'Back', competitions_admin_path %>

<div class="content-grids">

	<ul class="video-browsing">
		<% if @videos.count == 0 %>
			<div>
				<span>There is no videos matching the search keyword "<%= @param%>"</span>
			</div>
		<% else %>
<!--		<%= form_tag({:action => 'add_videos'} ) %>-->
				<% @videos.each do |v| %>
				<%= form_for(:post, :url => url_for(:controller => "competitions", :action => "add_videos"),html: {id: "add_video_to_competition_#{v.id}", class: "add_video_to_competition"}, remote: true) do |f| %>
				<div class="content-grid">
					<%= link_to image_tag(full_url(v.poster_url)), "#{videos_path}/#{v.id}", title: v.title, target: "_blank", class: "video-link", data: { no_turbolink: true } %>
					<h3><%= v.title %></h3>
					<%= f.hidden_field :video_id, value: v.id %>
					<%= f.hidden_field :competition_id, value: params[:cid] %>
					<%= f.submit "Add", class: "btn btn-primary" %>
					<!--<%= check_box_tag "#{v.id}" %>-->
				</div>
				
				<% end %>
				<% end %>
			<!--<%= submit_tag( "Submit" ) %>-->
		<% end %>
	</ul>
	<div class="clear"> </div>
	<%= will_paginate @videos %>
	<div class="clear"> </div>
</div>