config/routes.rb
Rails.application.routes.draw do
  root 'videos#show'
  
  get 'admin/videos'
  get 'admin/review/:id' => 'admin#review', :as => 'admin_review'
  post 'admin/approve' => 'admin#approve'
  get 'admin/vc_relations'
  post 'admin/vc_relations'
  get 'admin/vc_approve'

  get 'competitions/admin' => 'competitions#admin'
  get 'competitions/show_videos' => 'competitions#show_videos'
  post 'competitions/add_videos' => 'competitions#add_videos'
  get 'competitions/delete_videos' => 'competitions#delete_videos'

  resource :video_cart, only: [:show]
  resources :video_carts, only: [:destroy]
  resources :added_videos, only: [:create, :update, :destroy]
  resources :password_resets
  
  get 'register' => 'users#new', :as => 'register'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'videos/:id' => 'videos#show', :as => 'video_search'
  get 'videos/:search_params' => 'videos#search'
  post '/rate' => 'rater#create', :as => 'rate'

  
  resources :users, :sessions, :rater, :upload_videos, :videos, :admin, :competitions
  resources :videos do
    member do
      put "like" => "videos#upvote"
      put "unlike" => "videos#downvote"
    end
  end

end

app/views/admin/_video_profile.html.erb
<video id="myVideo" class="video-js video-in-detail vjs-big-play-centered" controls preload="auto" width="700" height="350"
poster="<%= full_url(@video.poster_url)%>" data-setup="{}">
<source src="<%= full_url(@video.video_url)%>" type="video/mp4">
	<p class="vjs-no-js">
		To view this video please enable JavaScript, and consider upgrading to a web browser that
		<a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
	</p>
</video>

app/views/admin/index.html.erb
<div class="right-content-heading">
  <div class="right-content-heading-left">
    <h3>Administration Page for CucuCity</h3>
  </div>
  <div class="clear"> </div>
</div>

<%= link_to 'Video Approval (To check whether videos uploaded can be shown on the website)', admin_videos_path(:approved => 0)%>
<br>

<%= link_to 'Video Approval to Participate in a Competition (To check whether videos uploaded can participate in a specific competition)', admin_vc_relations_path(:approved => 0)%>
<br>

<%= link_to 'Competition Management (To create or edit a competiton)', competitions_admin_path %>

app/views/admin/review.html.erb
<div class="right-content-heading">
	<div class="right-content-heading-left">
		<% if @is_search %>
		<h3>Search Results for <span class="keyword">"<%= @param%>"</span></h3>
		<% else %>
		<h3>reviewing <%= @video.title%></h3>
		<% end %>
	</div>
	<div class="right-content-heading-right">
	</div>
	<div class="clear"> </div>
</div>
<div class="content-grids">
	<h1>Video Profile: </h1>
	<div class="video-profile">
		<div>Title: <%= @video.title %></div> 
		<div>Uploader: <%= @video.user.username %></div>
		<div>Status:  <span><%= @str %></span></div>
	</div>
	<%= render partial: "video_profile", locals: {video: @video} %>
	
	<%= form_tag({controller: 'admin', action: 'approve'}, method: 'post', :id => 'review-form') do%>
 
	 <% if @video.is_approved != 1 %>
	 	<h1>Checklist: </h1>
		<ol>
		    <li><%= label_tag '1', "The user\'s historical data is acceptable. (The user #{@video.user.username} has #{@denied_size} videos denied)" %>
		    <%= check_box_tag 'c1', '1' %></li>

		    <li><%= label_tag '2', 'The length is acceptable. (The length of the video is 00:00)', {:id => 'time_label'}%>
		    <%= check_box_tag 'c2', '1' %></li>
		    <br>
		    <li><%= label_tag '3', 'The content and title of the video is acceptable:' %>
				<ol>

				<li><%= label_tag '3a', 'The title is consistent with the video content.' %>
			    <%= check_box_tag 'c3a', '1' %></li>
				<li><%= label_tag '3b', 'The video content is legal and does not violate any regulation.' %>
			    <%= check_box_tag 'c3b', '1' %></li>
				<li><%= label_tag '3c', 'The video content is consistent with the theme of the competition.' %>
			    <%= check_box_tag 'c3c', '1' %></li>
				</ol>
			</li>

	    </ol>
	<% end %>

    <%= hidden_field_tag 'review_action', '0'%>
    <%= hidden_field_tag 'vid', @video.id%>

    <% if @video.is_approved != 0 %>
    <%= submit_tag 'Pending' %>
    <% end %>
    <% if @video.is_approved != -1 %>
    <%= submit_tag 'Deny' %>
    <% end %>
    <% if @video.is_approved != 1 %>
    <%= submit_tag 'Approve', disabled: true%>
    <% end %>

    <% end %>
    <br/>
    <%= link_to 'Back', admin_videos_path(:approved => @video.is_approved), class: "ph-button ph-btn-grey" %>
    <div class="clear"> </div>
</div>

app/views/admin/vc_relations.html.erb
<div class="right-content-heading">
	<div class="right-content-heading-left">
		<h3>review <%= @str %> videos for competition "<%= @competition.title%>"</h3>

		<%= link_to "Approved Videos", admin_vc_relations_path(:approved => 1, :cid => @competition.id), title: "approved videos" %> | 
		<%= link_to "Pending Videos", admin_vc_relations_path(:approved => 0, :cid => @competition.id), title: "pending videos" %> | 
		<%= link_to "Denied Videos", admin_vc_relations_path(:approved => -1, :cid => @competition.id), title: "denied videos" %>
	</div>
	<div class="right-content-heading-right">
		
	</div>
	<div class="clear"> </div>
</div>

<div>
	<%= link_to '<< Back to upper level', admin_index_path%>
	<%= form_tag({controller: 'admin', action: 'vc_relations'}, method: 'post', :id => 'competition-form') do%>
		<%= select_tag "cid", options_from_collection_for_select(@competitions, "id", "title", @competition.id) %>
		<%= submit_tag "select" %>
	<% end %>
</div>
<div>
		<% if @vc_relations.count == 0 %>
			There is no <%= @str %> videos for the competition.
		<% end %>

    	<% @vc_relations.each do |v| %>
    	<div class="video_info"> 
			<div class="video_image">
				<%= link_to image_tag(full_url(v.video.poster_url)), video_path(:id => v.video.id), title: v.video.title, target: "_blank", data: { no_turbolink: true } %>
			</div>
			<div class="video_details">
				<div><span>Title:</span><%= v.video.title %></div>
				<div><span>Uploader:</span><%= v.video.user.username %></div>
				<div><span>Description:</span><%= v.video.video_desc %></div>
			</div>
			<div class="video_actions">
				<% if @approved == "0" || @approved == "-1" %>
					<%= link_to "Approve", admin_vc_approve_path(:id => v.id, :approved => 1, :ori => @approved), title: "Approve" %>
				<% end %>
				<% if @approved == "0" %> | <% end %>
				<% if @approved == "0" || @approved == "1" %>
					<%= link_to "Deny", admin_vc_approve_path(:id => v.id, :approved => -1, :ori => @approved), title: "Deny" %>
				<% end %>
			</div>
			<div class="clear"> </div>
		</div>
		<% end %>	
    
</div>

app/views/admin/videos.html.erb
<div class="right-content-heading">
	<div class="right-content-heading-left">
		<% if @is_search %>
		<h3>Search Results for <span class="keyword">"<%= @param%>"</span></h3>
		<% else %>
		<h3><%= @str%> videos</h3>
		<% end %>

		<%= link_to "Approved Videos", admin_videos_path(:approved => 1), title: "approved videos" %> | 
		<%= link_to "Pending Videos", admin_videos_path(:approved => 0), title: "pending videos" %> | 
		<%= link_to "Denied Videos", admin_videos_path(:approved => -1), title: "denied videos" %>
	</div>
	<div class="right-content-heading-right">
		
	</div>
	<div class="clear"> </div>
</div>
<div class="content-grids">
<%= link_to '<< Back to upper level', admin_index_path%><br>
	<ul class="video-browsing">
		<% if @videos_not_approved.count == 0 %>
		<div>
			<span>There is no <%= @str%> videos.</span>
		</div>
		<% else %>
		<% @videos_not_approved.each do |v| %>
		<div class="content-grid">
			<%= link_to image_tag(full_url(v.poster_url)), admin_review_path(:id => v.id), title: v.title, class: "video-link", data: { no_turbolink: true } %>
			<h3><%= v.title %></h3>
		</div>
		<% end %>
		<% end %>
	</ul>
	<div class="clear"> </div>
	<%= will_paginate @videos_not_approved %>
	<div class="clear"> </div>
</div>