config/routes.rb
Rails.application.routes.draw do
  root 'videos#show'
  
  get 'admin/videos'
  get 'admin/review/:id' => 'admin#review', :as => 'admin_review'
  post 'admin/approve' => 'admin#approve'
  get 'admin/vc_relations'
  post 'admin/vc_relations'
  get 'admin/vc_approve'

  get 'competitions/admin' => 'competitions#admin'
  get 'competitions/show_videos' => 'competitions#show_videos'
  post 'competitions/add_videos' => 'competitions#add_videos'
  get 'competitions/delete_videos' => 'competitions#delete_videos'

  resource :video_cart, only: [:show]
  resources :video_carts, only: [:destroy]
  resources :added_videos, only: [:create, :update, :destroy]
  resources :password_resets
  
  get 'register' => 'users#new', :as => 'register'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'videos/:id' => 'videos#show', :as => 'video_search'
  get 'videos/:search_params' => 'videos#search'
  post '/rate' => 'rater#create', :as => 'rate'

  
  resources :users, :sessions, :rater, :upload_videos, :videos, :admin, :competitions
  resources :videos do
    member do
      put "like" => "videos#upvote"
      put "unlike" => "videos#downvote"
    end
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  ratyrate_rateable 'visual_effects', 'entertainment'
  acts_as_votable
  has_many :vc_relations
  has_many :added_videos
  has_one :user, :primary_key => :uploader_id, :foreign_key => :id

  validates_presence_of :title
  validates_presence_of :video_url
  validates_presence_of :poster_url
  
  validates :title, length: { minimum: 2 }
  validates :title, length: { maximum: 50 }
  validates :video_desc, length: { maximum: 500 }

  validates_format_of :title, :with => /\A[0-9a-zA-Z\s\.\-\_]+\z/, :on => :create

  before_save :clean_link

  def clean_link
    self.video_url = self.video_url.split('amazonaws.com/').last
    self.poster_url = self.poster_url.split('amazonaws.com/').last
  end

  def self.search(search)
    if search
      self.where("title like ?", "%#{search}%")
    else
      find(:all)
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :upvote, :downvote]
  @@PER_PAGE = 12

  def index
    if params.has_key?(:search)
      @is_search = true
      param = params[:search]
      @param = param
      sql = "SELECT * FROM videos WHERE is_approved = 1 AND (title LIKE '%#{param}%' || video_desc LIKE '%#{param}%' || tags LIKE '%#{param}%')"
      @videos = Video.paginate_by_sql(sql, page: params[:page], per_page: @@PER_PAGE)
    else
      sql = "SELECT * FROM videos WHERE is_approved = 1"
      @videos = Video.paginate_by_sql(sql, page: params[:page], per_page: @@PER_PAGE)
      if @videos.count == 0
        redirect_to root_path
      end
    end
  end

  def show
    @uploader = User.find(@video[:uploader_id])
    if params.has_key?(:cid) and VcRelation.where(video_id: @video.id, competition_id: params[:cid]).count != 0
      @competition = Competition.find(params[:cid])
      @cid = @competition.id
    end
  end

  def new
  end

  def search
    
  end

  def upvote
    if !@competition_id
      render :json => "{\"err\": \"The video is not in a competition.\"}"
    else
      scope = "competition_" + @competition_id;
      @video.upvote_from current_user, vote_scope: scope
      upvotes = @video.get_upvotes(vote_scope: scope).size
      downvotes = @video.get_downvotes(vote_scope: scope).size
      render :json => "{\"id\": #{@video.id}, \"upvotes\": #{upvotes}, \"downvotes\": #{downvotes}}"
    end
  end

  def downvote
    if !@competition_id
      render :json => "{\"err\": \"The video is not in a competition.\"}"
    else
      scope = "competition_" + @competition_id;
      @video.downvote_from current_user, vote_scope: scope
      upvotes = @video.get_upvotes(vote_scope: scope).size
      downvotes = @video.get_downvotes(vote_scope: scope).size
      render :json => "{\"id\": #{@video.id}, \"upvotes\": #{upvotes}, \"downvotes\": #{downvotes}}"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.where(id: params[:id]).first
      @competition_id = params[:competition_id]
      if !@video
        redirect_to action: "index"
      end
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_voting.html.erb
<div class="video-vote">
  <%= link_to image_tag("dislike.png", size: "32x32", alt: "like"), '#', title: "unlike", class: "unlike", url: unlike_video_path(id: video.id, competition_id: competition_id) %>
  <span class="unlike-vote-<%= video.id %>"><%= video.get_downvotes(vote_scope: "competition_" + competition_id.to_s).size %></span>
</div>

<div class="video-vote">
<span>Vote for this video: </span>
  <%= link_to image_tag("like.png", size: "32x32", alt: "like"), '#', title: "like", class: "like", url: like_video_path(id: video.id, competition_id: competition_id) %>
  <span class="like-vote-<%= video.id %>"><%= video.get_upvotes(vote_scope: "competition_" + competition_id.to_s).size %></span>
 </div>

app/views/videos/index.html.erb
<div class="right-content-heading">
	<div class="right-content-heading-left">
		<% if @is_search %>
		<h3>Search Results for <span class="keyword">"<%= @param%>"</span></h3>
		<% else %>
		<h3>Trending Videos</h3>
		<% end %>
	</div>
	<div class="right-content-heading-right">
		<div class="social-icons">
			<ul>
				<li><a class="facebook" href="#" target="_blank"></a></li>
				<li><a class="twitter" href="#" target="_blank"></a></li>
				<li><a class="googleplus" href="#" target="_blank"></a></li>
				<li><a class="pinterest" href="#" target="_blank"></a></li>
				<li><a class="dribbble" href="#" target="_blank"></a></li>
				<li><a class="vimeo" href="#" target="_blank"></a></li>
			</ul>
		</div>
	</div>
	<div class="clear"> </div>
</div>


<% if !@is_search %>	
	<div class="video-show" style="@import url(https://fonts.googleapis.com/css?family=Roboto:300); background:#e4e2e9; margin-bottom:20px;  font-family: 'Roboto', sans-serif; padding: 10px">
  		<h3>Welcome to CucuCity</h3> <br>
  		The website that makes you laugh, smile and cry in under 30 seconds! You can check out <%= link_to "videos which are trending", root_path %> or <%= link_to "participate in a competition", competitions_path %> by <%= link_to "uploading your own video", upload_videos_path %> and win prize money. You can also vote for videos that you like by exploring competitions on the left in order to determine the winner of each competition.
	</div>
<% end %>

<div class="content-grids">
	<ul class="video-browsing">
		<% if @videos.count == 0 %>
			<div>
				<span>There is no videos matching the search keyword "<%= @param%>"</span>
			</div>
		<% else %>
			<% @videos.each do |v| %>
			<div class="content-grid">
				<%= link_to image_tag(full_url(v.poster_url)), "#{videos_path}/#{v.id}", title: v.title, class: "video-link", data: { no_turbolink: true } %>
				<h3><%= v.title %></h3>
				
				<%= link_to "Watch now", "#{videos_path}/#{v.id}", title: v.title, class: "button", data: { no_turbolink: true } %>
			</div>
			<% end %>
		<% end %>
	</ul>
	<div class="clear"> </div>
	<%= will_paginate @videos %>
	<div class="clear"> </div>
</div>

app/views/videos/new.html.erb
<h1>Videos#new</h1>
<p>Find me in app/views/videos/new.html.erb</p>

app/views/videos/show.html.erb
<div class="right-content-heading">
  <div class="right-content-heading-left">
    <h3><%= @video.title%></h3>
  </div>
  <div class="right-content-heading-right">
    <div class="social-icons">
      <ul>
        <li><a class="facebook" href="#" target="_blank"> </a></li>
        <li><a class="twitter" href="#" target="_blank"></a></li>
        <li><a class="googleplus" href="#" target="_blank"></a></li>
        <li><a class="pinterest" href="#" target="_blank"></a></li>
        <li><a class="dribbble" href="#" target="_blank"></a></li>
        <li><a class="vimeo" href="#" target="_blank"></a></li>
      </ul>
    </div>
  </div>
  <div class="clear"> </div>
</div>

<div class="inner-page">
    <div class="video-detail">
      <video id="myVideo" class="video-js video-in-detail vjs-big-play-centered" controls preload="auto" width="700" height="350"
      poster="<%= full_url(@video.poster_url)%>" data-setup="{}">
      <source src="<%= full_url(@video.video_url)%>" type="video/mp4">
        <p class="vjs-no-js">
          To view this video please enable JavaScript, and consider upgrading to a web browser that
          <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
        </p>
      </video>

      <div class="rate-and-vote">
        <% if !@competition%>
        <div class="video-rate"><%= rating_for @video, "entertainment" %></div>
        <% else %>
        <%= render partial: "voting", locals: {video: @video, competition_id: @competition.id} %>
        <% end %>
      </div>

    </div>
    <% if current_user %>
    <%= hidden_field_tag(id = 'user-info', value = current_user.id, options = {}) %>
    <% end %>
  <div class="clear"> </div>
  <div class="video-details">
    <h1>Video Information: </h1><hr>
    <ul>
      <li><p>Uploaded on <%= @video.created_at %> by <!--<a href="#">-->@<%= @uploader.username %><!--</a>--></p></li>
      <li><span><%= @video.video_desc %></span></li>
    </ul>
  </div>
  <div class="clear"> </div>
  <div class="tags">
    <ul>
      <li><h3>Tags:</h3></li>

      <% @video.tags.split(",").each do |tag| %>
      <li><span class="tag"><%= link_to tag, :controller => "videos", :search => tag, :utf8 => "✓"%></span></li>
      <% end %>
    </ul>
  </div>
  <% if @competition%>
  <div class="competition-info tags">
    <ul>
      <li><h3><br/>Competition Information:</h3></li>
    </ul>
    <div class="comp-desc-left">
      <p>
        <img src="<%= full_url(@competition.poster) %>"/>
      </p>
    </div>
    <div class="comp-desc-right">
      <p id="notice"><%= notice %></p>
        </p>
      <p>
        <strong>Desc:</strong>
        <%= @competition.desc %>
      </p>

      <p>
        <strong>Start date:</strong>
        <%= @competition.start_date %>
      </p>

      <p>
        <strong>Period:</strong>
        <%= @competition.period %>
      </p>

      <p>
        <strong>Prize:</strong>
        <%= @competition.prize %>
      </p>

      <p>
        <strong>Prize num:</strong>
        <%= @competition.prize_num %>
      </p>
      
    </div>
  </div>
  <% end%>
  <div class="clear"> </div>
  
</div>