config/routes.rb
Rails.application.routes.draw do
  root 'videos#show'
  
  get 'admin/videos'
  get 'admin/review/:id' => 'admin#review', :as => 'admin_review'
  post 'admin/approve' => 'admin#approve'
  get 'admin/vc_relations'
  post 'admin/vc_relations'
  get 'admin/vc_approve'

  get 'competitions/admin' => 'competitions#admin'
  get 'competitions/show_videos' => 'competitions#show_videos'
  post 'competitions/add_videos' => 'competitions#add_videos'
  get 'competitions/delete_videos' => 'competitions#delete_videos'

  resource :video_cart, only: [:show]
  resources :video_carts, only: [:destroy]
  resources :added_videos, only: [:create, :update, :destroy]
  resources :password_resets
  
  get 'register' => 'users#new', :as => 'register'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'videos/:id' => 'videos#show', :as => 'video_search'
  get 'videos/:search_params' => 'videos#search'
  post '/rate' => 'rater#create', :as => 'rate'

  
  resources :users, :sessions, :rater, :upload_videos, :videos, :admin, :competitions
  resources :videos do
    member do
      put "like" => "videos#upvote"
      put "unlike" => "videos#downvote"
    end
  end

end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_competition.vc_relations.size} Videos in List", video_cart_path + "?cid=#{session[:competition_id]}", class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CucuCity | <%= (params[:controller]).humanize.titleize %></title>
  <%= favicon_link_tag 'logo.png', type: 'image/png'  %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <% if current_user %>
      <% if current_user.username %>
        <div class="welcome">Hi, <%= current_user.username %></div>
      <% else %>
        <div class="welcome">Hi, <%= current_user.email %></div>
      <% end %>
      <div class="clear"></div>
    <% end %>

    <div class="wrap">
      <div class="logo">
        <%= link_to image_tag('logo.png', height: '70px'), root_path, title: 'logo' %>
      </div>
      <div class="top-menu">
        <div class="search">
          <%= form_tag videos_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search" %> 
          <%= submit_tag "", :name => nil %>
          <% end %>
        </div>
        <div class="top-nav">
          <ul>
            <li><%= link_to "Trending", root_path %></li>
            <li><%= link_to "Competitions", competitions_path %></li>
            <% if current_user %>
            <li><%= link_to "Upload", upload_videos_path %></li>
            <li><%= link_to "logout", logout_path %></li>
            <% else %>
            <li><a href="#">About</a></li>
            <li><%= link_to "login", login_path %></li>
            <% end %>
          </ul>
        </div>
        <div class="clear"> </div>
      </div>
      <div class="clear"> </div>
    </div>
  </div>
  <div class="clear"> </div>
  <div class="main-content">
    <div class="wrap">
      <div class="left-sidebar">
        <div class="sidebar-boxs">

          <div class="clear"> </div>
          <div class="type-videos">
            <h3>Active Competitions</h3>
            <ul>
            <% all_competitions.each do |c| %>
              <li><%= link_to "#{c.title}", "#{competitions_path}/#{c.id}"%> </li>
            <% end%>
            </ul>
          </div>
        </div>
      </div>
      <div class="right-content">

        <%= yield %>

      </div>
      <div class="clear"> </div>
    </div>
  </div>
  <div class="clear"> </div>
  <div class="copy-right">
    <p>Copyright 2016. All Rights Reserved</p>
  </div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag params[:controller], 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CucuCity</title>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>

	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag params[:controller], 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CucuCity</title>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>

	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag params[:controller], 'data-turbolinks-track' => true %>
</body>
</html>